### ISSUE TITLE
1.20.4 Error on each custom head fish

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [Oheers/EvenMoreFish#357] opened 2024-05-30 18:32 UTC
Hey, we've updated to 1.20.4 these days and noticed that whenever a tournament is running and people fish the emf custom head fishes, that on each of those special fish, we get several messages in the console, repeating itself. This example is by catching 1 of those custom head fishes:

`[20:21:19 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
[20:21:19 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
[20:21:19 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
[20:21:19 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
[20:21:19 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).`

Best regards.

**Comment by sarhatabaot** [comment] 2024-06-12 17:22
Duplicate of #344 . Fixed in latest dev builds.

**Closed by sarhatabaot** 2024-06-12 17:22 UTC
Labels: bug: confirmed, duplicate, bug: fixed
