### ISSUE TITLE
[Bug]: Console warn

### ISSUE THREAD

**Issue by VentureStudios** [Oheers/EvenMoreFish#428] opened 2024-09-11 08:33 UTC
### What happened?

[10:32:20 WARN]: [EvenMoreFish] "EvenMoreFish v1.7.3" has registered a listener for com.destroystokyo.paper.event.brigadier.CommandRegisteredEvent on method "public void com.oheers.fish.libs.acf.PaperBrigadierManager.onCommandRegister(com.destroystokyo.paper.event.brigadier.CommandRegisteredEvent<com.destroystokyo.paper.brigadier.BukkitBrigadierCommandSource>)", but the event is Deprecated. "This event has been superseded by the Commands API and will be removed in a future release. Listen to LifecycleEvents.COMMANDS instead."; please notify the authors [Oheers].

### Version

Development

### Development Version

1.7.3#110

### Server Version

1.21.1 Pupperfish

### Java Version

21

**Comment by sarhatabaot** [comment] 2024-09-12 07:19
Duplicate of #359

**Closed** 2024-09-12 07:19 UTC
Labels: bug: unconfirmed
